//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScanGifDir {
	
	
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("ICSharpCode.SettingsEditor.SettingsCodeGeneratorTool", "5.1.0.5216")]
	internal sealed partial class Init : global::System.Configuration.ApplicationSettingsBase {
		
		private static Init defaultInstance = ((Init)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Init())));
		
		public static Init Default {
			get {
				return defaultInstance;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("\"\"")]
		public string DirPathShow {
			get {
				return ((string)(this["DirPathShow"]));
			}
			set {
				this["DirPathShow"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
		public global::System.Drawing.Size FormSize {
			get {
				return ((global::System.Drawing.Size)(this["FormSize"]));
			}
			set {
				this["FormSize"] = value;
			}
		}
	}
}
